apiVersion: console.streamshub.github.com/v1alpha1 # Versão da API do recurso customizado da Streams Console
kind: Console # Tipo do recurso que está sendo criado
metadata: # Metadados do objeto Kubernetes
  name: console # Nome do recurso Console
  namespace: kafka # Namespace onde a Console será criada
spec: # Especificação principal da Console
  hostname: console-kafka.apps.cluster-bg4d4.bg4d4.sandbox3088.opentlc.com

  security: # Bloco de segurança da Console
    oidc: # Configuração de autenticação via OIDC (OpenID Connect)
      authServerUrl: https://keycloak-service-kafka.apps.cluster-bg4d4.bg4d4.sandbox3088.opentlc.com/realms/Kafka
      #authServerUrl: <URL-KEYCLOAK>/realms/kafka # URL do realm no RHBK/Keycloak usado para autenticar os usuários
      clientId: streams-console # Client ID cadastrado no Keycloak para a aplicação Console
      clientSecret: # Referência ao client secret do OIDC
        valueFrom: # Indica que o valor será obtido de outro recurso Kubernetes
          secretKeyRef: # Busca o valor em um Secret
            name: my-oidc-secret # Nome do Secret que armazena o client secret
            key: client-secret # Chave dentro do Secret que contém o client secret

# caso seja necessario certificado para confiar no rhbk     
#      trustStore:
#        type: PEM
#        content:
#          valueFrom:
#            configMapKeyRef:
#              name: keycloak-ca-cert
#              key: ca.crt
      grantType: AUTHORIZATION_CODE
      scopes: "openid profile email"

    subjects:
      - claim: groups
        include:
          - administrators
        roleNames:
          - administrators
      - claim: groups
        include:
          - developers
        roleNames:
          - developers

    roles:
      - name: administrators
        rules:
          - resources:
              - kafkas
            privileges:
              - ALL
      - name: developers
        rules:
          - resources:
              - kafkas
            privileges:
              - ALL

  kafkaClusters:
    - name: kafka-cluster
      namespace: kafka
      listener: plain
      credentials:
        kafkaUser:
          name: app-user

      security:
        roles:
          - name: developers
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                privileges:
                  - GET
                  - LIST
          - name: administrators
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes
                  - nodes/configs
                privileges:
                  - GET
                  - LIST
              - resources:
                  - consumerGroups
                  - rebalances
                privileges:
                  - UPDATE
